id: https://ch.paf.link/schema/session
name: ch-paf-link-session
prefixes:
  xsd: http://www.w3.org/2001/XMLSchema#
  prov: http://www.w3.org/ns/prov#
  dcterm: http://purl.org/dc/terms/
  linkml: https://w3id.org/linkml/
  paf: https://paf.link/
  chpaf: https://ch.paf.link/
  parl: https://politics.ld.admin.ch/parliamentary_affair/
imports:
  - linkml:types
default_prefix: chpaf
default_range: string
  
classes:
  
  Session:
    slots:
      - id
      - name
      - agendaItems

  AgendaItem:
    slots:
      - id
      - name
      - votes

  Vote:
    slots:
      - id
      - question
      - result

  Container:
    tree_root: true
    slots:
      - id
      - sessions

slots:
  
  id:
    identifier: true
    required: true

  name:
    slot_uri: dcterm:title
    range: string
    required: true

  sessions:
    slot_uri: chpaf:session
    range: Session
    multivalued: true
    inlined_as_list: true
  
  agendaItems:
    slot_uri: chpaf:agendaItem
    range: AgendaItem
    multivalued: true
    inlined_as_list: true
  
  votes:
    slot_uri: chpaf:vote
    range: Vote
    multivalued: true
    inlined_as_list: true

  question:
    range: string
    required: true
  
  result:
    range: result_enum
    required: true

enums:

  result_enum:
    permissible_values:
      "yes":
        meaning: chpaf:results/yes
      "no":
        meaning: chpaf:results/no
