id: https://ch.paf.link/schema/actors
name: PersonSchema
title: Person Schema
description: A schema describing a person with addresses, names, languages, citizenships, occupations, training, and contact details.
license: CC-BY

prefixes:
  linkml: https://w3id.org/linkml/
  act: https://ch.paf.link/schema/actors/
  dcterm: http://purl.org/dc/terms/

default_prefix: ex
default_range: string

imports:
  - linkml:types

classes:

  Container:
    tree_root: true
    slots:
      - Person

  MultilingualString:
    slots:
      - text
      - language
      
  Person:
    description: A person with identifiers, names, addresses, citizenships, and occupations.
    attributes:
      id:
        identifier: true
        required: true
      label:
        description: Display name of the person
        required: true
      label_long:
        description: Extended display name (with title, etc.)
      birthyear:
        range: integer
      birthdate:
        range: date
      picture:
        description: Link to an image (preferred: PNG, then JPG, then GIF)
      names:
        range: Name
        multivalued: true
      addresses:
        range: Address
        multivalued: true
      languages:
        range: LanguageProficiency
        multivalued: true
      ch_citizenship:
        range: Validity
      citizenships:
        range: Citizenship
        multivalued: true
      genders:
        range: Gender
        multivalued: true
      occupations:
        range: Occupation
        multivalued: true
      training:
        range: Training
        multivalued: true
      contacts:
        range: Contact
        multivalued: true

  Name:
    attributes:
      nameType:
        range: NameTypeEnum
        required: true
      value:
        required: true
      validFrom:
        range: date
      validUntil:
        range: date

  Address:
    attributes:
      addressType:
        range: AddressTypeEnum
        required: true
      addressURI:
        description: Preferred URI of address
      streetAddress:
      postalCode:
      postalLocality:

  LanguageProficiency:
    attributes:
      language:
        description: ISO language code
        required: true
      correspondence:
        range: boolean
      native:
        range: boolean

  Validity:
    attributes:
      validFrom:
        range: date
      validUntil:
        range: date

  Citizenship:
    is_a: Validity
    attributes:
      country:
        description: ISO 3166 country code
        required: true

  Gender:
    is_a: Validity
    attributes:
      gender:
        description: Gender code
        required: true
      pronouns:

  Occupation:
    is_a: Validity
    attributes:
      active:
        range: boolean
      paid:
        range: boolean
      occupation_isco19_code:
      occupation:
      enterprise_uid:
      enterprise:

  Training:
    attributes:
      type:
        range: TrainingTypeEnum
        required: true
      training_isco19_code:
      training:

  Contact:
    attributes:
      type:
        range: ContactTypeEnum
        required: true
      contact:
        required: true

enums:
  NameTypeEnum:
    permissible_values:
      familyNameOnForeignPassport:
      callName:

  AddressTypeEnum:
    permissible_values:
      privateAddress:
      businessAddress:
      localAddress:

  TrainingTypeEnum:
    permissible_values:
      schulabschluss:
      efz:
      uni:
      armee:
      zivi:
      zischutz:

  ContactTypeEnum:
    permissible_values:
      email:
      contact_website:
      linked-in:
      twitter:
