id: https://ch.paf.link/schema/operations
name: ch-paf-link-operations
description: "Meeting Schema for various legislative bodies"
prefixes:
  linkml: https://w3id.org/linkml/
  ops: https://ch.paf.link/schema/operations/
  dcterm: http://purl.org/dc/terms/
imports:
  - linkml:types
default_prefix: ops
default_range: string

classes:
  
  Container:
    tree_root: true
    slots:
      - id
      - meetings

  MultilingualString:
    slots:
      - text
      - language

  Meeting:
    slots:
      - id
      - body_key
      - name
      - url
      - number
      - abbreviation
      - group_name
      - group_id
      - begin_date
      - end_date
      - state
      - description
      - location
      - type
      - updated_datetime
      - created_datetime
    
slots:
  
  id:
    identifier: true
    required: true
    slot_uri: dcterm:identifier
  body_key:
  name:
    range: MultilingualString
    multivalued: true
    inlined_as_list: true
  url:
    range: MultilingualString
    multivalued: true
    inlined_as_list: true
  number:
  abbreviation:
  group_name:
  group_id:
  begin_date:
    range: datetime
  end_date:
    range: datetime
  state:
  description:
  location:
  updated_datetime:
  created_datetime:
  meetings:
    slot_uri: ops:meeting
    range: Meeting
    multivalued: true
    inlined_as_list: true
  text:
    required: true

  language:
    required: true
    description: "Language code in ISO 639-1 format"
    pattern: ^[a-z]{2}$
