id: https://ch.paf.link/schema/operations
name: operations
description: "Meeting Schema for various legislative bodies"
prefixes:
  linkml: https://w3id.org/linkml/
  ops: https://ch.paf.link/schema/operations/
  dcterm: http://purl.org/dc/terms/
imports:
  - linkml:types
default_prefix: ops
default_range: string

classes:

  Container:
    tree_root: true
    slots:
      - id
      - legislatures
      - sessions
      - meetings
      - meeting_items

  MultilingualString:
    slots:
      - text
      - language

  Legislature:
   description: >-
      [en] Term of office of a parliament as a legislative assembly. Usually lasts four years. >-
      [de] Amtsdauer eines Parlaments als gesetzgebender Versammlung. Dauert in der Regel vier Jahre.
    slots:
      - id # technical ID 
      - administrative_id # administrative body of the legislation (muni, canton, country) 
      - name # human readable name
      - description      
      - landing_page # if available link to an url which provides further information
      - actor_id # the political body which is organized by the term of office (Regierungsrat, Nationalrat, Ständerat)
      - begin_date # meta
      - end_date # meta
      - updated_datetime  # meta
      - created_datetime # meta


  Meeting:
    description: >-
      [en] A general meeting class used for Sessions, Comittee Meetings, invidiual session Sittings and other various Meetings. >-
      [de] Eine allgemeine Sitzungsklasse, die für Sessionen, Kommissionssitzungen, Sessionsitzung und andere verschiedene Versammlungen verwendet wird.
    slots:
      - id
      - type  #define enum (session, committee, sitting, various) #sitting=Sessionsitzung, 
      - administrative_id 
      - name
      - landing_page
      - sequential_number # Laufnummer (string, because roman literals etc.)
      - position # integer in line with the sequential_number
      - abbreviation # 
      - actor_name # name of the political body (e.g. "Nationalrat")
      - actor_id 
      - begin_date # planned
      - end_date # planned
      - begin_date_actual
      - end_date_actual
      - state # enum planned, moved, closed etc.
      - state_name # for other state descriptions      
      - description 
      - location # If in person, where the meeting will be held.
      - parent_meeting_id # Meetings are hierarchicaly structured, the linked meeting_id which is grouping the current meeting.
      - parent_legislature_id # Legislation in which the meeting is based.
      - updated_datetime
      - created_datetime
      
  AgendaItem:
    description: >-
      [en] An agenda item of a meeting. >-
      [de] Ein Traktandum einer Sitzung.  
    slots:
      - id
      - meeting_id # the connection of the 
      - type  #traktandum oder Traktandengruppen)
      - date_time
      - date_time_actual
      - number # number (string, because roman literals etc.)
      - position # integer
      - leading_actor_id # Federführendes Departement
      - speaking_actor_id # Sprecher oder Departamentsvorsteher
      - title
      - affair_id # the connection to the affairs (business items) of the agenda item
      - description #Untertitel, Traktandendetails
      - state_id # enum planned, moved, closed etc.
      - state_name # for other state descriptions
      - landing_page # 
      - category # grouped agenda items (e.g. introduction, by department, technical agenda items etc.)
      - parent_agenda_item_id # if needed to build a hierarchy of agenda items
      - resolution # range "Resolution" 
      - updated_datetime
      - created_datetime

JointDebate: 
  description: >-
    [en] Agenda Items which are debated together. >-
    [de] Traktanden die gemeinsam behandelt werden.
  slots:
    - meetingItem

Resolution:
  slots:
    - type # annahme, ablehnung, kenntnisnahmme, punktweise annahme, annahme mit postulat, mündlich erledigt, beinahe einstimmig, other
    - type_label # Wenn nicht standardisiert, dann wird hier der Typ ausgegeben und bei type auf other gesetzt
    - vote_procedures # [0:n] 

Voting:
  slots:
    - id # Ratssystem ID / Abstimmungslagen ID
    - datetime_begin # Datum und Zeit Abstimmungsbegin
    - datetime_end # Datum und Zeit Abstimmungsende
    - type #zwischenabstimmung, schlussabstimmung, Stichentscheid Präsidium?, geheime Wahl/Abstimmung
    - type_label
    - title #Abstimmungstitel bzw. Gegenstand / Frage. Wenn kein Gegestand vorhanden, dann sollte nicht der Geschäftstitel angegeben werden
        - optional
    - landing_page # URL für Abstimmungs PDF/HTML
    - meaning_of_yes # Bedeutung bei einem Ja
    - meaning_of_no # Bedeutung bei einem Nein
    - meaning_of_abstention # Bedeutung bei 3 Knopf - Selten belegt mit drei Optionen
    - total_yes
    - total_no
    - total_abstention
    - total_absent # Präsident Abstimmung? # Unterscheidung abwesend/entschuldigt anwesend wird auf Anwesenheitsliste
    - total # Anzahl yes, no, abstention (ohne absent und ohne Präsident)
    - absulte_majority # Absolutes Mehr
    - result_text # freitext zum Beschrieb des Outcomens , z.B. "Mit 78 Stimmen angenommen"
    - meeting_id # Abstimmung gehört zu Meeting
    - agenda_item_ids # Abgestimmung gehört zu Traktandum
    - affairs_ids #
    - actor_id # Gremium (Rat, aber auch Kommission, Landsgemeinde, Volk) 
    - updated_datetime
    - created_datetime

# Handling Präsidiums-Votum wird als eigenes voting aufgenommen


Vote:
  slots:
      - id
      - voting_id # link zu abstimmung
      - actor_id # Person
      - type # yes, no, abstention, absent, absent_excused, abstention_president, other
      - type_label # Anzeige des der Abstimmung (z.B. Für oder Gegen Abstimmungsgegenstand)
      - updated_datetime
      - created_datetime



      
slots:

  id:
    identifier: true
    required: true
    slot_uri: dcterm:identifier
  
  body_key:
  
  name:
    range: MultilingualString
    multivalued: true
    inlined_as_list: true
  
  url:
    range: MultilingualString
    multivalued: true
    inlined_as_list: true
  
  number:
  
  abbreviation:
  
  group_name:
  
  group_id:
  
  begin_date:
    range: date

  begin_date_actual:
    range: date
  
  end_date:
    range: date

  end_date_actual:
    range: date

  date_time:
    range: datetime

  date_time_actual:
    range: datetime
  
  state:
    range: state_enum

  status:

  type:
  
  description:
  
  location:

  position:

  result:

  title:

  category:
  
  updated_datetime:
    range: datetime
    description: "The last time this record was updated"
  
  created_datetime:
    range: datetime
    description: "The time this record was created"

  affairs:

  legislatures:
    slot_uri: ops:legislature
    range: Legislature
    multivalued: true
    inlined_as_list: true

  sessions:
    slot_uri: ops:session
    range: Session
    multivalued: true
    inlined_as_list: true
  
  meetings:
    slot_uri: ops:meeting
    range: Meeting
    multivalued: true
    inlined_as_list: true

  meeting_items:
    slot_uri: ops:meetingItem
    range: MeetingItem
    multivalued: true
    inlined_as_list: true
  
  text:
    required: true
  
  language:
    required: true
    description: "Language code in ISO 639-1 format"
    pattern: ^[a-z]{2}$

enums:

  state_enum:
    description: "State of the meeting"
    permissible_values:
      "planned":
        meaning: ops:state/planned
      "canceled":
        meaning: ops:state/canceled
      "postponed":
        meaning: ops:state/postponed
