id: https://ch.paf.link/schema/operations
name: operations
description: "Meeting Schema for various legislative bodies"
prefixes:
  linkml: https://w3id.org/linkml/
  ops: https://ch.paf.link/schema/operations/
  dcterm: http://purl.org/dc/terms/
imports:
  - linkml:types
default_prefix: ops
default_range: string

classes:

  Container:
    tree_root: true
    slots:
      - id
      - legislatures
      - sessions
      - meetings
      - meeting_items

  MultilingualString:
    slots:
      - text
      - language

  Legislature:
    slots:
      - id
      - body_key
      - name
      - url
      - description
      - group_name
      - group_id
      - begin_date
      - end_date
      - updated_datetime
      - created_datetime


  Meeting:
    slots:
      - id
      - type  #define enum (session, committee, sitting, various) #sitting=Sessionsitzung, 
      - body_key
      - name
      - url
      - number
      - abbreviation
      - group_name
      - group_id
      - begin_date
      - end_date
      - begin_date_actual
      - end_date_actual
      - state
      - description
      - location
      - submeeting_id #linked meeting_id
      - updated_datetime
      - created_datetime
      

  MeetingItem:
    slots:
      - id
      - meeting
      - type  #traktandum oder Traktandengruppen)
      - date_time
      - date_time_actual
      - position
      - leading #Federführendes Departement
      - speaker #Sprecher oder Departamentsvorsteher
      - number
      - title
      - affairs
      - description #Unteritel, Traktandendetails
      - status
      - url
      - category
      - subMeetingItem_id
      - result
      - updated_datetime
      - created_datetime

JointDebate  #Traktanden die gemeinsam behandelt werden
  slots:
    - meetingItem

Decison
  slots
    -   

slots:

  id:
    identifier: true
    required: true
    slot_uri: dcterm:identifier
  
  body_key:
  
  name:
    range: MultilingualString
    multivalued: true
    inlined_as_list: true
  
  url:
    range: MultilingualString
    multivalued: true
    inlined_as_list: true
  
  number:
  
  abbreviation:
  
  group_name:
  
  group_id:
  
  begin_date:
    range: date

  begin_date_actual:
    range: date
  
  end_date:
    range: date

  end_date_actual:
    range: date

  date_time:
    range: datetime

  date_time_actual:
    range: datetime
  
  state:
    range: state_enum

  status:

  type:
  
  description:
  
  location:

  position:

  result:

  title:

  category:
  
  updated_datetime:
    range: datetime
    description: "The last time this record was updated"
  
  created_datetime:
    range: datetime
    description: "The time this record was created"

  affairs:

  legislatures:
    slot_uri: ops:legislature
    range: Legislature
    multivalued: true
    inlined_as_list: true

  sessions:
    slot_uri: ops:session
    range: Session
    multivalued: true
    inlined_as_list: true
  
  meetings:
    slot_uri: ops:meeting
    range: Meeting
    multivalued: true
    inlined_as_list: true

  meeting_items:
    slot_uri: ops:meetingItem
    range: MeetingItem
    multivalued: true
    inlined_as_list: true
  
  text:
    required: true
  
  language:
    required: true
    description: "Language code in ISO 639-1 format"
    pattern: ^[a-z]{2}$

enums:

  state_enum:
    description: "State of the meeting"
    permissible_values:
      "planned":
        meaning: ops:state/planned
      "canceled":
        meaning: ops:state/canceled
      "postponed":
        meaning: ops:state/postponed
