#
# Syntaktisch korrekte Version
# bitte in schema_working.yaml arbeiten!
#

id: https://ch.paf.link/schema/consultation
name: ch-paf-link-consultation
prefixes:
  xsd: http://www.w3.org/2001/XMLSchema#
  prov: http://www.w3.org/ns/prov#
  dcterm: http://purl.org/dc/terms/
  linkml: https://w3id.org/linkml/
  paf: https://paf.link/
  chpaf: https://ch.paf.link/
  con: https://politics.ld.admin.ch/consultation/
imports:
  - linkml:types
default_prefix: chpaf
default_range: string
  
classes:
  
  Consultation:
    slots:
      - id
      - name
      - content
      - receivers

  Container:
    tree_root: true
    slots:
      - id
      - consultations

slots:
  
  id:
    identifier: true
    required: true

  name:
    slot_uri: dcterm:title
    range: string
    required: true

  content:
    required: true

  receivers:
    slot_uri: chpaf:receiver
    multivalued: true
    inlined_as_list: true

  consultations:
    slot_uri: chpaf:consultation
    range: Consultation
    multivalued: true
    inlined_as_list: true