name: Consultation

on:
  push:
    paths:
      - 'consultation/input/schema.yaml'
      - 'consultation/input/data.yaml'
  workflow_dispatch:

jobs:
  consultation:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Clean output directory
        run: rm -rf consultation/output/*

      - name: Convert schema.yaml to schema.json
        run: |
          mkdir -p consultation/output
          gen-json-schema consultation/input/schema.yaml > consultation/output/schema.json

      - name: Convert schema.yaml to schema.ttl
        run: |
          mkdir -p consultation/output
          gen-owl consultation/input/schema.yaml > consultation/output/schema.ttl

      - name: Convert data.yaml to data.json
        run: |
          mkdir -p consultation/output
          linkml-convert -s consultation/input/schema.yaml -t json consultation/input/data.yaml > consultation/output/data.json

      - name: Convert data.yaml to data.ttl
        run: |
          mkdir -p consultation/output
          linkml-convert -s consultation/input/schema.yaml -t rdf consultation/input/data.yaml > consultation/output/data.ttl

      - name: Generate documentation
        run: |
          mkdir -p consultation/output/docs
          gen-doc consultation/input/schema.yaml --directory consultation/output/docs

      - name: Commit and push changes
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add consultation/output/
            git diff --quiet && git diff --staged --quiet || git commit -m "Auto-generated consultation files"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
