name: Gx_tutorial

on:
  push:
    paths:
      - 'Gx_tutorial/input/**'
  workflow_dispatch:

jobs:
  Gx_tutorial:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Clean output directory
        run: rm -rf Gx_tutorial/output/*

      - name: Convert schema.yaml to schema.json
        run: |
          mkdir -p Gx_tutorial/output
          gen-json-schema Gx_tutorial/input/schema.yaml > Gx_tutorial/output/schema.json

      - name: Convert schema.yaml to schema.ttl
        run: |
          mkdir -p Gx_tutorial/output
          gen-owl Gx_tutorial/input/schema.yaml > Gx_tutorial/output/schema.ttl

      - name: Convert all data_*.yaml to data_*.json
        run: |
          mkdir -p Gx_tutorial/output
          for yaml_file in Gx_tutorial/input/data_*.yaml; do
            base_name=$(basename "$yaml_file" .yaml)
            linkml-convert -s Gx_tutorial/input/schema.yaml -t json "$yaml_file" > "Gx_tutorial/${base_name}.json"
          done

      - name: Convert data_*.yaml to data_*.ttl
        run: |
          mkdir -p Gx_tutorial/output
          for yaml_file in Gx_tutorial/input/data_*.yaml; do
            base_name=$(basename "$yaml_file" .yaml)
            linkml-convert -s Gx_tutorial/input/schema.yaml -t rdf "$yaml_file" > "Gx_tutorial/output/${base_name}.ttl"
          done

      - name: Generate LinkML documentation
        run: |
          mkdir -p Gx_tutorial/output/docs
          gen-doc Gx_tutorial/input/schema.yaml --directory Gx_tutorial/output/docs
      - name: Merge Markdown documentation
        run: python merge_documentation.py Gx_tutorial
      - name: Install Pandoc
        run: sudo apt update && sudo apt install -y pandoc

      - name: Convert Markdown to Word with Pandoc
        run: |
          mkdir -p Gx_tutorial/output
          pandoc Gx_tutorial/output/documentation_merged.md \
          -o Gx_tutorial/output/tutorial.docx \
          --reference-doc=Gx_tutorial/input/template.docx

      - name: Commit and push changes
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add tutorial/output/
            git diff --quiet && git diff --staged --quiet || git commit -m "Auto-generated tutorial files"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
