name: Tutorial

on:
  push:
    paths:
      - 'tutorial/input/**'
  workflow_dispatch:

jobs:
  tutorial:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Clean output directory
        run: rm -rf tutorial/output/*

      - name: Convert schema.yaml to schema.json
        run: |
          mkdir -p tutorial/output
          gen-json-schema tutorial/input/schema.yaml > tutorial/output/schema.json

      - name: Convert schema.yaml to schema.ttl
        run: |
          mkdir -p tutorial/output
          gen-owl tutorial/input/schema.yaml > tutorial/output/schema.ttl

      - name: Convert data.yaml to data.json
        run: |
          mkdir -p tutorial/output
          linkml-convert -s tutorial/input/schema.yaml -t json tutorial/input/data.yaml > tutorial/output/data.json

      - name: Convert data.yaml to data.ttl
        run: |
          mkdir -p tutorial/output
          linkml-convert -s tutorial/input/schema.yaml -t rdf tutorial/input/data.yaml > tutorial/output/data.ttl

      - name: Generate LinkML documentation
        run: |
          mkdir -p tutorial/output/docs
          gen-doc tutorial/input/schema.yaml --directory tutorial/output/docs
      - name: Merge Markdown documentation
        run: python merge_documentation.py tutorial
      - name: Install Pandoc
        run: sudo apt update && sudo apt install -y pandoc

      - name: Convert Markdown to Word with Pandoc
        run: |
          mkdir -p tutorial/output
          pandoc tutorial/output/documentation_merged.md \
          -o tutorial/output/tutorial.docx \
          --reference-doc=tutorial/input/template.docx

      - name: Commit and push changes
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add tutorial/output/
            git diff --quiet && git diff --staged --quiet || git commit -m "Auto-generated tutorial files"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
